<?php
/**
 * Title: Dashless landing
 * Slug: dashless/landing
 * Categories: dashless
 * Inserter: no
 */
?>
<!-- wp:html -->
<section class="dl-studio-layout" id="start" aria-labelledby="hero-title">
<div class="dl-studio-photo"><picture><source srcset="<?php echo esc_url(get_theme_file_uri('assets/webp/studio-minimal-storefront-hd.webp')); ?>" type="image/webp"><img src="<?php echo esc_url(get_theme_file_uri('assets/studio-minimal-storefront-hd.png')); ?>" width="1024" height="1536" fetchpriority="high" decoding="async" alt="A crisp minimal illustration of a sunlit neighborhood bookshop with paper ephemera and a bicycle."></picture><span class="dl-paper-note">Good stories<br>live here.</span></div>
<div class="dl-studio-copy dl-intro"><p class="dl-eyebrow">YOUR OWN LITTLE CORNER OF THE INTERNET.</p><h1 id="hero-title">A small<br>publishing studio<br>for a <em>kinder internet.</em></h1><p class="dl-studio-deck">For people who care about what they put into the world.</p><p class="dl-no-admin">Your ideas. Your own blog.<br>Write, design, and publish with ChatGPT.</p>
<!-- /wp:html -->
<!-- wp:dashless/login-button /-->
<!-- wp:html -->
<p class="dl-studio-price">$9.99 / month · Your domain. Your writing.</p></div>
<div class="dl-studio-zine"><figure><picture><source srcset="<?php echo esc_url(get_theme_file_uri('assets/webp/studio-minimal-zine-hd.webp')); ?>" type="image/webp"><img src="<?php echo esc_url(get_theme_file_uri('assets/studio-minimal-zine-hd.png')); ?>" width="1536" height="1024" loading="lazy" decoding="async" alt="A crisp minimal illustration of a handmade zine with landscape photographs, pressed flowers and paper scraps."></picture><figcaption>Small ideas. Bigger, braver stories.</figcaption></figure><div class="dl-night-postcard"><picture><source srcset="<?php echo esc_url(get_theme_file_uri('assets/webp/studio-minimal-night-hd.webp')); ?>" type="image/webp"><img src="<?php echo esc_url(get_theme_file_uri('assets/studio-minimal-night-hd.png')); ?>" width="1254" height="1254" loading="lazy" decoding="async" alt="A crisp minimal illustration of a welcoming neighborhood bookshop street at night."></picture><p>Same streets.<br>New stories. ☾</p></div></div>
<section class="dl-theme-gallery" id="themes" aria-labelledby="themes-title">
<div class="dl-theme-gallery-head"><div><p class="dl-eyebrow">FIND A LOOK THAT FEELS LIKE YOU.</p><h2 id="themes-title">Themes <span aria-hidden="true">—</span></h2></div><p>Find a look that feels like you.</p></div>
<div class="dl-theme-grid">
<article class="dl-theme-card dl-theme-card--field"><a href="#account"><img src="<?php echo esc_url(get_theme_file_uri('assets/theme-preview-field-notes.png')); ?>" width="1280" height="1000" loading="lazy" alt="Screenshot of the Field Notes theme in use."><span class="dl-theme-arrow" aria-hidden="true">↗</span></a><div class="dl-theme-card-copy"><p class="dl-theme-kicker">01 / FIELD NOTES</p><h3>Field Notes</h3><p>For walks, places, recipes, and the small observations worth keeping.</p></div></article>
<article class="dl-theme-card dl-theme-card--after"><a href="#account"><img src="<?php echo esc_url(get_theme_file_uri('assets/theme-preview-after-hours.png')); ?>" width="1280" height="1000" loading="lazy" alt="Screenshot of the After Hours theme in use."><span class="dl-theme-arrow" aria-hidden="true">↗</span></a><div class="dl-theme-card-copy"><p class="dl-theme-kicker">02 / AFTER HOURS</p><h3>After Hours</h3><p>For midnight notes, city lights, playlists, and the thoughts that arrive after dark.</p></div></article>
<article class="dl-theme-card dl-theme-card--hyper"><a href="#account"><img src="<?php echo esc_url(get_theme_file_uri('assets/theme-preview-hypertext-diary.png')); ?>" width="1280" height="1000" loading="lazy" alt="Screenshot of the Hypertext Diary theme in use."><span class="dl-theme-arrow" aria-hidden="true">↗</span></a><div class="dl-theme-card-copy"><p class="dl-theme-kicker">03 / HYPERTEXT DIARY</p><h3>Hypertext Diary</h3><p>For links, fragments, references, and a mind that refuses to stay in one tab.</p></div></article>
</div>
<p class="dl-theme-gallery-note">Different is a feature. <a href="<?php echo esc_url(home_url('/themes/')); ?>">See all six themes ↗</a></p>
</section>
</section>
<section class="dl-studio-steps" id="how-it-works" aria-labelledby="steps-title"><div class="dl-steps-heading"><h2 id="steps-title">How it works</h2><p>THREE SIMPLE STEPS.</p></div><ol class="dl-steps" aria-label="How Dashless works">
<li><span class="dl-step-number">01</span><div><h3>Pick your address.</h3><p>Bring your own domain, or use an included .dashless.blog address.</p><span class="dl-step-sketch" aria-hidden="true">⌂</span></div></li>
<li><span class="dl-step-number">02</span><div><h3>Make it yours.</h3><p>Pick a theme. Shape your words, photos, and ideas with ChatGPT.</p><span class="dl-step-sketch" aria-hidden="true">✎</span></div></li>
<li><span class="dl-step-number">03</span><div><h3>Preview. Approve. Publish.</h3><p>Take a look. Make your final tweaks. Share your blog with the world.</p><span class="dl-step-sketch" aria-hidden="true">↗</span></div></li>
</ol><p class="dl-steps-note">A kinder internet<br>is a few brave<br>people away. ♡</p></section>
<section class="dl-example dl-example--collage" id="live-demo" aria-labelledby="example-title">
<div class="dl-example-copy"><p class="dl-eyebrow">MADE WITH DASHLESS</p><h2 id="example-title">Small problems.<br>Real live blog.</h2><p>Missing scissors. Mysterious fridge noises. A chair with too many responsibilities. Meet the Department of Small Problems.</p><a class="dl-paper-button dl-demo-link" href="https://smallproblems.dashless.blog/">Explore the live example <span aria-hidden="true">↗</span></a></div>
<div class="dl-example-collage"><picture><source srcset="<?php echo esc_url(get_theme_file_uri('assets/webp/studio-minimal-chair-hd.webp')); ?>" type="image/webp"><img class="dl-chair-photo" src="<?php echo esc_url(get_theme_file_uri('assets/studio-minimal-chair-hd.png')); ?>" width="1536" height="1024" loading="lazy" decoding="async" alt="A crisp minimal illustration of a wooden chair with books, an olive jacket and a coffee mug."></picture><p class="dl-example-note">Real stories.<br>Not perfect<br>ones. ♡</p><a class="dl-example-preview" href="https://smallproblems.dashless.blog/" aria-label="Explore the Small Problems example blog"><img src="<?php echo esc_url(get_theme_file_uri('assets/small-problems-home-desktop.png')); ?>" width="1440" height="2193" loading="lazy" decoding="async" alt="Actual homepage of The Department of Small Problems."><span>A real blog.<br>A real human. ↗</span></a><p class="dl-example-label">Made with<br>Dashless.<br>All yours. ♡</p></div></section>
<section class="dl-bottom-grid dl-bottom-grid--collage" aria-label="Pricing and questions">
<figure class="dl-pricing-photo"><picture><source srcset="<?php echo esc_url(get_theme_file_uri('assets/webp/studio-minimal-desk-hd.webp')); ?>" type="image/webp"><img src="<?php echo esc_url(get_theme_file_uri('assets/studio-minimal-desk-hd.png')); ?>" width="1536" height="1024" loading="lazy" decoding="async" alt="A crisp minimal illustration of a desk with coffee, postcards, flowers, a notebook and a fountain pen."></picture><figcaption>Same place.<br>Different perspective. ♡</figcaption></figure>
<div class="dl-price-ticket" id="pricing"><h2>One blog. All yours.</h2><p class="dl-plan-price">$9.99 <span>/ month</span></p><ul class="dl-price-features"><li>WordPress hosting</li><li>Your own domain</li><li>Private previews</li><li>Your writing to keep</li></ul><p class="dl-caption">ChatGPT access is separate.<br>No annual commitment.<br>Applicable taxes are shown at checkout.</p><a class="dl-paper-button" href="#start">Make it yours <span aria-hidden="true">→</span></a></div>
<div class="dl-questions"><h2>A few good questions.</h2><p class="dl-questions-intro">Straight answers for curious humans.</p>
<details><summary>Do I need to learn WordPress?<span aria-hidden="true">+</span></summary><p>No. ChatGPT already knows WordPress, so you don’t have to. Write posts, shape your design, and preview changes through conversation. You approve what goes live. You never need to log into WP-Admin.</p></details>
<details><summary>Do I own my writing?<span aria-hidden="true">+</span></summary><p>Yes. Your content lives in WordPress. You can export it and take it with you.</p></details>
<details><summary>Do I need a WordPress account?<span aria-hidden="true">+</span></summary><p>No. Start with your email, and we’ll take care of the rest. Auth0 keeps your sign-in secure. Your writing and design happen in ChatGPT; Dashless handles your blog, account, and billing.</p></details>
<details><summary>How does ChatGPT connect?<span aria-hidden="true">+</span></summary><p>Once your blog is ready, connect Dashless in ChatGPT. Draft, design, and review private previews through conversation. You approve what goes live. The ChatGPT connection is awaiting release.</p></details>
<details><summary>Can I cancel?<span aria-hidden="true">+</span></summary><p>Yes, through your account’s billing portal. Your blog stays available through the paid period, followed by 30 days to recover or export your content.</p></details>
<details><summary>Can I bring my own domain?<span aria-hidden="true">+</span></summary><p>Yes—custom domains are part of the Dashless offer. Use a domain you own, or choose an included .dashless.blog address. Once your blog is ready, add your domain from your account and follow the short DNS checklist. Domain registration stays with you; Dashless handles the connection and HTTPS.</p></details>
<p class="dl-questions-signoff"><span aria-hidden="true">❧</span> Different questions.<br>Same brighter internet.</p></div></section>
<!-- /wp:html -->
<!-- wp:dashless/home-account /-->
<!-- wp:dashless/home-help /-->
