<?php
/**
 * Title: Dashless landing
 * Slug: dashless/landing
 * Categories: dashless
 * Inserter: no
 */
?>
<!-- wp:group {"align":"wide","className":"dl-hero","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide dl-hero">
<!-- wp:paragraph {"className":"dl-eyebrow"} --><p class="dl-eyebrow"><span class="dl-dot">●</span> WORDPRESS POWER. CHATGPT POSSIBILITY.</p><!-- /wp:paragraph -->
<!-- wp:columns {"className":"dl-hero-columns"} --><div class="wp-block-columns dl-hero-columns"><!-- wp:column {"width":"57%"} --><div class="wp-block-column" style="flex-basis:57%">
<!-- wp:heading {"level":1,"className":"dl-hero-title"} --><h1 class="wp-block-heading dl-hero-title">Less admin.<br><em>More you.</em></h1><!-- /wp:heading -->
<!-- wp:paragraph {"className":"dl-hero-copy"} --><p class="dl-hero-copy">The power of WordPress. The possibility of ChatGPT.<br>A real home for your ideas, with a whole new way to create. Write, shape, and publish through conversation. We handle the hosting and setup.</p><!-- /wp:paragraph -->
<!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="/sign-in/">Start with WordPress.com ↗</a></div><!-- /wp:button --></div><!-- /wp:buttons -->
<!-- wp:paragraph {"className":"dl-small"} --><p class="dl-small">$9.99 / month · Your own .dashless.blog address</p><!-- /wp:paragraph -->
<!-- wp:dashless/launch-note /-->
<!-- wp:html --><a class="dl-cloud-badge" href="https://wp.cloud/"><span aria-hidden="true">☁</span> Powered by <strong>WP Cloud</strong> <span aria-hidden="true">↗</span></a><!-- /wp:html -->
</div><!-- /wp:column --><!-- wp:column {"width":"43%"} --><div class="wp-block-column" style="flex-basis:43%">
<!-- wp:html --><div class="dl-demo" aria-label="Illustration of drafting and previewing a blog"><div class="dl-demo-top"><span>AN IDEA, WITH SOMEWHERE TO GO.</span><span>↗</span></div><div class="dl-demo-chat"><span class="dl-demo-avatar" aria-hidden="true">y</span><p>Make my blog feel like a little independent magazine.</p></div><div class="dl-demo-paper"><div class="dl-demo-paper-meta">YOUR CORNER OF THE INTERNET <span>01</span></div><h2>Notes from<br>the in-between.</h2><div class="dl-demo-art" aria-hidden="true"><svg viewBox="0 0 400 115" fill="none"><path d="M0 82C46 10 84 130 132 54S210 18 243 72 313 40 347 22 388 75 400 62" stroke="currentColor" stroke-width="3"/><circle cx="304" cy="45" r="30" stroke="currentColor" stroke-width="2"/><path d="M48 90 66 20 89 83 19 46 102 47Z" stroke="currentColor" stroke-width="2"/></svg></div><p>A place for the things you notice.<br>And the things you can’t stop thinking about.</p><div class="dl-demo-paper-footer">YOUR WORDS. YOUR CALL. <span>✳</span></div></div><div class="dl-demo-stamp">You approve.<br>Then it goes live.</div><p class="dl-demo-caption">Illustrative preview. Your blog starts with a blank page.</p></div><!-- /wp:html -->
</div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->
<!-- wp:html -->
<section class="dl-live-demo" id="live-demo" aria-labelledby="live-demo-title">
  <div class="dl-live-demo-heading"><div><p class="dl-eyebrow">A SMALL BLOG. A WHOLE WORLD.</p><h2 id="live-demo-title">Take a look<br><em>around.</em></h2></div><div class="dl-live-demo-copy"><h3>The Department of Small Problems</h3><p>Missing scissors. Suspicious fridge noises. A chair with too many responsibilities. Seven stories from a very fictional department, on a real Dashless example blog.</p><a class="dl-button dl-demo-link" href="https://smallproblems.dashless.blog/">Explore the live blog <span aria-hidden="true">↗</span></a><p class="dl-small">Read a story, try the search, and switch between light and dark.</p></div></div>
  <a class="dl-demo-screens" href="https://smallproblems.dashless.blog/" aria-label="Visit The Department of Small Problems example blog">
    <figure class="dl-screen-desktop"><div class="dl-screen-bar"><span aria-hidden="true">● ● ●</span><span>smallproblems.dashless.blog</span><span aria-hidden="true">↗</span></div><img src="<?php echo esc_url(get_theme_file_uri('assets/small-problems-desktop.jpg')); ?>" alt="The Department of Small Problems homepage, with an illustrated chair investigation and a collection of stories." width="1440" height="1050" loading="lazy" decoding="async"></figure>
    <figure class="dl-screen-mobile"><img src="<?php echo esc_url(get_theme_file_uri('assets/small-problems-mobile.jpg')); ?>" alt="A Small Problems story on a phone, showing its headline and chair illustration." width="390" height="844" loading="lazy" decoding="async"></figure>
  </a>
  <p class="dl-demo-footnote">Screenshots of the live example. Fictional stories; a real site you can explore.</p>
</section>
<!-- /wp:html -->
<!-- wp:html -->
<section class="dl-workflow" aria-labelledby="workflow-title">
  <div class="dl-workflow-heading"><div><p class="dl-eyebrow">THE BEST OF BOTH WORLDS. IN ONE FLOW.</p><h2 id="workflow-title">From a thought<br>to <em>your thing.</em></h2></div><p>Create with ChatGPT.<br>Make it yours with WordPress.</p></div>
  <div class="dl-walkthrough" data-dl-walkthrough>
    <div class="dl-flow-steps" aria-label="Explore an example publishing flow">
      <button type="button" class="dl-flow-step" data-step="draft" aria-pressed="true" aria-controls="dl-flow-draft"><span class="dl-flow-number">01</span><span><strong>Make a draft.</strong><small>A rough thought is enough to start.</small></span><span aria-hidden="true">↗</span></button>
      <button type="button" class="dl-flow-step" data-step="preview" aria-pressed="false" aria-controls="dl-flow-preview"><span class="dl-flow-number">02</span><span><strong>See your page.</strong><small>Read it. Rearrange it. Make it yours.</small></span><span aria-hidden="true">↗</span></button>
      <button type="button" class="dl-flow-step" data-step="publish" aria-pressed="false" aria-controls="dl-flow-publish"><span class="dl-flow-number">03</span><span><strong>You say publish.</strong><small>Only the version you approve goes live.</small></span><span aria-hidden="true">↗</span></button>
      <p class="dl-flow-disclosure">An illustrative walkthrough, not a live ChatGPT session. Nothing you click here publishes anything.</p>
    </div>
    <div class="dl-flow-stage">
      <div class="dl-flow-panel" id="dl-flow-draft"><p class="dl-preview-bar"><span>IN THE CONVERSATION</span><span>Draft / 01</span></p><div class="dl-conversation"><p class="dl-human-note">I’ve been taking the long way home. Help me turn these notes into a short post. Keep it in my voice.</p><p class="dl-assistant-note">Here’s a starting point. What would you change?</p><div class="dl-draft-excerpt"><span class="dl-example-kicker">A DRAFT, NOT A DEADLINE</span><h3>The long way home.</h3><p>I took the street with the trees today. It added ten minutes. I’m beginning to think those were the good ten minutes.</p><span class="dl-saved-state">Draft saved · Only you can see it</span></div></div><button class="dl-flow-next" type="button" data-next="preview">See the example preview <span aria-hidden="true">→</span></button></div>
      <div class="dl-flow-panel" id="dl-flow-preview" hidden><p class="dl-preview-bar"><span>PRIVATE PREVIEW</span><span>02 / Your blog</span></p><article class="dl-example-post"><div class="dl-example-masthead"><strong>The scenic route</strong><span>field notes &amp; small detours</span></div><p class="dl-example-kicker">NOTES FROM AN ORDINARY TUESDAY</p><h3>The long<br>way home.</h3><div class="dl-route-art" aria-hidden="true"><svg viewBox="0 0 420 90" fill="none"><path d="M0 66H80C155 66 110 16 185 16S227 76 301 76 339 36 420 36" stroke="currentColor" stroke-width="3"/><circle cx="80" cy="66" r="6" fill="currentColor"/><circle cx="340" cy="65" r="6" fill="currentColor"/></svg><span>A LITTLE OFF THE USUAL PATH ↗</span></div><p>I took the street with the trees today. It added ten minutes. I’m beginning to think those were the good ten minutes.</p><p class="dl-example-byline">A note by you. On a site that feels like you.</p></article><button class="dl-flow-next" type="button" data-next="publish">See the approval step <span aria-hidden="true">→</span></button></div>
      <div class="dl-flow-panel" id="dl-flow-publish" hidden><p class="dl-preview-bar"><span>YOUR FINAL SAY</span><span>03 / Approval</span></p><div class="dl-approval-example"><span class="dl-approval-mark" aria-hidden="true">↗</span><p class="dl-example-kicker">READY WHEN YOU ARE</p><h3>This version.<br>Your decision.</h3><p>You’ve read the preview. You like the words, the design, and the way it all fits together.</p><div class="dl-approved-post"><span>THE POST</span><strong>The long way home.</strong><span>THE VERSION</span><strong>The preview you just reviewed</strong></div><p class="dl-publish-specimen"><span aria-hidden="true">✓</span> Publish this version <small>Example approval control</small></p><p class="dl-approval-note">In Dashless, you approve the preview yourself. A conversation alone doesn’t publish it.</p></div><button class="dl-flow-next" type="button" data-next="draft">Back to the first thought <span aria-hidden="true">↺</span></button></div>
    </div>
  </div>
</section>
<!-- /wp:html -->
<!-- wp:group {"align":"wide","anchor":"how-it-works","className":"dl-process","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide dl-process" id="how-it-works"><!-- wp:paragraph {"className":"dl-eyebrow"} --><p class="dl-eyebrow">GETTING YOUR BLOG TOGETHER</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">A name. A conversation.<br>A place of your own.</h2><!-- /wp:heading -->
<!-- wp:columns --><div class="wp-block-columns"><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"dl-step"} --><p class="dl-step">01 / GET YOUR PLACE</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Pick a name.</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Choose your address. We set up your WordPress blog, hosting, and a clean starting design.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"dl-step"} --><p class="dl-step">02 / MAKE IT YOURS</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Have a conversation.</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Connect Dashless in ChatGPT. Shape your design, work on a draft, or bring an old idea back to life.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"dl-step"} --><p class="dl-step">03 / PUT IT OUT THERE</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Give it the go-ahead.</h3><!-- /wp:heading --><!-- wp:paragraph --><p>See the actual preview. Make your changes. Nothing publishes until you approve it.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->
<!-- wp:html -->
<section class="dl-cloud-trust" aria-labelledby="dl-cloud-title"><div><p class="dl-eyebrow">A LITTLE BLOG. A SOLID FOUNDATION.</p><h2 id="dl-cloud-title">Your words.<br>In good company.</h2><a class="dl-cloud-badge" href="https://wp.cloud/"><span aria-hidden="true">☁</span> Powered by <strong>WP Cloud</strong> <span aria-hidden="true">↗</span></a></div><div class="dl-cloud-copy"><p>ChatGPT opens up a new way to create. WordPress gives what you create a home. Your writing lives on a real website you can share, grow, and export—not just inside a conversation.</p><p>Underneath it all is <strong>WP Cloud</strong>, built by the team behind WordPress.com, with a global CDN, automatic failover, a web application firewall, and DDoS protection. Fresh possibilities. An established foundation.</p><p class="dl-cloud-label">ALSO CHOSEN BY</p><div class="dl-cloud-names"><span>Pressable</span><span>Porkbun</span><span>Convesio</span></div><p class="dl-cloud-source">These are WP Cloud customers, not Dashless endorsements. <a href="https://wp.cloud/">Explore the platform and customer stories ↗</a></p></div></section>
<!-- /wp:html -->
<!-- wp:group {"align":"wide","anchor":"pricing","className":"dl-pricing","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide dl-pricing" id="pricing"><!-- wp:columns {"verticalAlignment":"center"} --><div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><!-- wp:paragraph {"className":"dl-eyebrow"} --><p class="dl-eyebrow">ONE BLOG. ONE SIMPLE PLAN.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Your words.<br>Your web.</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Your content lives in WordPress. You can export it. Your published blog stays online even when you close ChatGPT.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"center","className":"dl-price-card"} --><div class="wp-block-column is-vertically-aligned-center dl-price-card"><!-- wp:paragraph {"className":"dl-price"} --><p class="dl-price">$9.99 <span>USD / month</span></p><!-- /wp:paragraph --><!-- wp:list --><ul class="wp-block-list"><!-- wp:list-item --><li>One WordPress blog, hosted on WP Cloud</li><!-- /wp:list-item --><!-- wp:list-item --><li>Your own name.dashless.blog address</li><!-- /wp:list-item --><!-- wp:list-item --><li>Design and publish with ChatGPT</li><!-- /wp:list-item --><!-- wp:list-item --><li>Private previews. Your final approval.</li><!-- /wp:list-item --><!-- wp:list-item --><li>Cancel from your account</li><!-- /wp:list-item --></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="/sign-in/">Start with WordPress.com ↗</a></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:dashless/launch-note /-->
<!-- wp:paragraph {"className":"dl-small"} --><p class="dl-small">ChatGPT access is separate. No annual commitment.<br>Applicable taxes, if any, are shown at checkout.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->

<!-- wp:html -->
<section class="dl-faq" aria-labelledby="dl-faq-title"><div><p class="dl-eyebrow">YOUR IDEAS DESERVE A HOME</p><h2 id="dl-faq-title">Big possibilities.<br>Simple answers.</h2></div><div class="dl-faq-list">
<details><summary>What makes WordPress and ChatGPT so good together?<span aria-hidden="true">+</span></summary><p>WordPress gives you a publishing platform built to last: your own site, your own address, and content you can take with you. ChatGPT gives you a new way to work: turn a thought into a draft, explore a design, and refine it through conversation. Dashless brings them together, with a preview you approve before anything goes live.</p></details>
<details><summary>Why Dashless instead of setting up a blog myself?<span aria-hidden="true">+</span></summary><p>Because you came to write, not manage a website. Dashless brings your WordPress blog, hosting, design, and publishing into one flow with ChatGPT. Start with an idea, see how it looks on your site, and give it the go-ahead. We handle the setup in between.</p></details>
<details><summary>Will it sound like me—and look like my own site?<span aria-hidden="true">+</span></summary><p>That’s the point. Bring a finished piece, a messy draft, or a few notes. Ask for as much or as little help as you want, then shape the look with curated design choices. You review the actual preview and choose what goes live. Your name is on it. You get the final say.</p></details>
<details><summary>Can I use my own domain?<span aria-hidden="true">+</span></summary><p>Your own address belongs in the picture. Custom domain support is planned for launch, so you’ll be able to bring a domain you already own. Every blog also gets a name.dashless.blog address to start with. Domain registration and renewal are separate; the connection flow is still being built.</p></details>
<details><summary>What does my $9.99 a month cover?<span aria-hidden="true">+</span></summary><p>One WordPress blog, hosting on WP Cloud, your dashless.blog address, and the Dashless connection for designing, drafting, previewing, and publishing through ChatGPT. One monthly plan, with no annual commitment. Bring your own ChatGPT access; that subscription isn’t included.</p></details>
<details><summary>Why have a blog when I can just post on social media?<span aria-hidden="true">+</span></summary><p>Give your best ideas a place people can come back to. A blog puts your writing together under your own address, with room for the whole thought. Share the link anywhere. Your published site stays online when you close ChatGPT.</p></details>
<details><summary>Do I keep my writing if I leave?<span aria-hidden="true">+</span></summary><p>Yes. Your content lives in its own WordPress installation and you can export it. Cancel from your account whenever you like. Your blog stays online through your paid period, followed by 30 days to recover or export your content.</p></details>
</div></section>
<!-- /wp:html -->
