<?php
/**
 * Title: Dashless landing
 * Slug: dashless/landing
 * Categories: dashless
 * Inserter: no
 */
?>
<!-- wp:group {"align":"wide","className":"dl-hero","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide dl-hero">
<!-- wp:paragraph {"className":"dl-eyebrow"} --><p class="dl-eyebrow"><span class="dl-dot">●</span> WORDPRESS WITHOUT THE DASHBOARD.</p><!-- /wp:paragraph -->
<!-- wp:columns {"className":"dl-hero-columns"} --><div class="wp-block-columns dl-hero-columns"><!-- wp:column {"width":"57%"} --><div class="wp-block-column" style="flex-basis:57%">
<!-- wp:heading {"level":1,"className":"dl-hero-title"} --><h1 class="wp-block-heading dl-hero-title">Less admin.<br><em>More you.</em></h1><!-- /wp:heading -->
<!-- wp:paragraph {"className":"dl-hero-copy"} --><p class="dl-hero-copy">A blog that feels like yours.<br>Make it, write it, and publish it with ChatGPT. We’ll take care of the WordPress setup.</p><!-- /wp:paragraph -->
<!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="/sign-in/">Give your words a home ↗</a></div><!-- /wp:button --></div><!-- /wp:buttons -->
<!-- wp:paragraph {"className":"dl-small"} --><p class="dl-small">$9.99 / month · Your own .dashless.blog address</p><!-- /wp:paragraph -->
<!-- wp:dashless/launch-note /-->
</div><!-- /wp:column --><!-- wp:column {"width":"43%"} --><div class="wp-block-column" style="flex-basis:43%">
<!-- wp:html --><div class="dl-demo" aria-label="Illustration of drafting and previewing a blog"><div class="dl-demo-top"><span>AN IDEA, WITH SOMEWHERE TO GO.</span><span>↗</span></div><div class="dl-demo-chat"><span class="dl-demo-avatar" aria-hidden="true">y</span><p>Make my blog feel like a little independent magazine.</p></div><div class="dl-demo-paper"><div class="dl-demo-paper-meta">YOUR CORNER OF THE INTERNET <span>01</span></div><h2>Notes from<br>the in-between.</h2><div class="dl-demo-art" aria-hidden="true"><svg viewBox="0 0 400 115" fill="none"><path d="M0 82C46 10 84 130 132 54S210 18 243 72 313 40 347 22 388 75 400 62" stroke="currentColor" stroke-width="3"/><circle cx="304" cy="45" r="30" stroke="currentColor" stroke-width="2"/><path d="M48 90 66 20 89 83 19 46 102 47Z" stroke="currentColor" stroke-width="2"/></svg></div><p>A place for the things you notice.<br>And the things you can’t stop thinking about.</p><div class="dl-demo-paper-footer">YOUR WORDS. YOUR CALL. <span>✳</span></div></div><div class="dl-demo-stamp">You approve.<br>Then it goes live.</div><p class="dl-demo-caption">Illustrative preview. Your blog starts with a blank page.</p></div><!-- /wp:html -->
</div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"dl-manifesto","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide dl-manifesto"><!-- wp:paragraph --><p>Not another place to manage.<br><strong>A place to make something.</strong></p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"align":"wide","anchor":"how-it-works","className":"dl-process","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide dl-process" id="how-it-works"><!-- wp:paragraph {"className":"dl-eyebrow"} --><p class="dl-eyebrow">FROM “WHAT IF” TO YOUR OWN WEBSITE</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Talk it through.<br>Make it real.</h2><!-- /wp:heading -->
<!-- wp:columns --><div class="wp-block-columns"><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"dl-step"} --><p class="dl-step">01 / GET YOUR PLACE</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Pick a name.</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Choose your address. We set up your WordPress blog, hosting, and a clean starting design.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"dl-step"} --><p class="dl-step">02 / MAKE IT YOURS</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Have a conversation.</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Connect Dashless in ChatGPT. Shape your design, work on a draft, or bring an old idea back to life.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"className":"dl-step"} --><p class="dl-step">03 / PUT IT OUT THERE</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Give it the go-ahead.</h3><!-- /wp:heading --><!-- wp:paragraph --><p>See the actual preview. Make your changes. Nothing publishes until you approve it.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->
<!-- wp:group {"align":"wide","anchor":"pricing","className":"dl-pricing","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide dl-pricing" id="pricing"><!-- wp:columns {"verticalAlignment":"center"} --><div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center"} --><div class="wp-block-column is-vertically-aligned-center"><!-- wp:paragraph {"className":"dl-eyebrow"} --><p class="dl-eyebrow">ONE BLOG. ONE SIMPLE PLAN.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Your corner.<br>Keep the keys.</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Your content lives in WordPress. You can export it. Your published blog stays online even when you close ChatGPT.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"center","className":"dl-price-card"} --><div class="wp-block-column is-vertically-aligned-center dl-price-card"><!-- wp:paragraph {"className":"dl-price"} --><p class="dl-price">$9.99 <span>USD / month</span></p><!-- /wp:paragraph --><!-- wp:list --><ul class="wp-block-list"><!-- wp:list-item --><li>One hosted WordPress blog</li><!-- /wp:list-item --><!-- wp:list-item --><li>Your own name.dashless.blog address</li><!-- /wp:list-item --><!-- wp:list-item --><li>Design and publish with ChatGPT</li><!-- /wp:list-item --><!-- wp:list-item --><li>Private previews. Your final approval.</li><!-- /wp:list-item --><!-- wp:list-item --><li>Cancel from your account</li><!-- /wp:list-item --></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="/sign-in/">Start your next chapter ↗</a></div><!-- /wp:button --></div><!-- /wp:buttons --><!-- wp:paragraph {"className":"dl-small"} --><p class="dl-small">ChatGPT access is separate. No annual commitment.<br>Applicable taxes, if any, are shown at checkout.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->
