<?php
namespace Dashless\Hub;

/** Public policy copy, synchronized with submission materials. */
final class Policies {
    public static function content(string $slug): string {
        return match($slug) {
            'privacy' => <<<'PRIVACY'
<p><strong>Effective September 16, 2026.</strong> Dashless is operated by Izzi’s Gym LLC, doing business as Regionally Famous, in South Dakota, United States. Contact <a href="mailto:howdy@regionallyfamous.com">howdy@regionallyfamous.com</a> for privacy questions or requests.</p>
<h2>Information we process</h2>
<p>We process your Auth0 account ID, verified email address and display name to identify your account; blog settings, drafts, revisions, published posts, images, alternative text and design choices to provide your blog; subscription and invoice references and payment status to administer access; and job, authorization, security and support records to operate and troubleshoot the service. Requests can include technical information such as an IP address, browser information and timestamps. Please do not put passwords, payment-card details or other unnecessary sensitive information in blog content or support messages.</p>
<h2>How information is used and shared</h2>
<p>We use this information to authenticate you, perform the editorial actions you request, build and host your site, administer your subscription, answer support requests, prevent abuse and meet applicable legal obligations. Auth0 handles sign-in and authorizes the ChatGPT connection. Dashless validates those credentials but does not store your password or provider access and refresh tokens. A secure browser cookie keeps you signed in.</p>
<p>WP Cloud hosts the account service and blog data. Railway processes copies of content, media and design settings to build your site. Cloudflare provides domain, network and email-routing services. Stripe processes payments when billing is available; Dashless retains payment references rather than full payment-card numbers. Our email providers process support and service messages. These providers may process information in the United States and other countries.</p>
<p>When you connect ChatGPT, the tools return content, settings, theme choices and operation results needed for your requested actions to OpenAI. Images you select in ChatGPT can be transferred to your blog. OpenAI’s own terms, privacy controls and data practices govern your use of ChatGPT. Disconnecting Dashless does not erase an existing ChatGPT conversation. Publishing makes the approved content and included media publicly accessible; readers, search engines and other third parties may copy it.</p>
<h2>Cookies and access</h2>
<p>Dashless uses essential cookies for sign-in, account sessions, private previews and protection against forged requests. Private preview access requires authorization. Publication and rollback require approval in your signed-in browser. You can disconnect ChatGPT from your Dashless account to revoke its existing access and refresh-token chains.</p>
<h2>Retention</h2>
<p>We keep blog content and account records while providing the service. After paid access ends, the service provides a 30-day recovery and export period before the site becomes eligible for deletion. Deletion is processed after checking current subscription status; it is not an instantaneous erasure of every provider backup or record. A reserved blog name may remain unavailable after deletion to prevent old links from being reassigned to another person.</p>
<p>Railway build data is scheduled for cleanup after 24 hours. Private preview access expires after 24 hours; this access deadline is not a promise that stored preview or export artifacts are erased at that moment. Those artifacts can remain with the site until removed during maintenance or site deletion. Hub audit records are scheduled to expire after 90 days. Short-lived authorization and security records expire according to their purpose and are removed by maintenance.</p>
<p>Account, billing, job and support records, and hosting-provider backups, may be retained separately where needed to provide recovery, resolve a request or dispute, prevent fraud, or meet legal obligations. Contact us to request deletion or to ask which records remain and why. We verify ownership before acting on requests and explain any applicable retention requirement or technical limitation.</p>
<h2>Your choices and requests</h2>
<p>You can edit your blog, export its content and source, and disconnect ChatGPT through the available account and editorial controls. To request access, correction, deletion, restriction or portability of your personal information, or to object to processing where applicable, email our privacy contact above. Depending on your location, you may have additional rights, including raising a concern with your local privacy regulator. We handle requests according to applicable law. Removing content from Dashless does not remove copies held independently by readers, search engines or other services.</p>
<p>Dashless is intended for adults and is not directed to children. If you believe a child has provided personal information, contact us. We will post material changes to this notice here and use account contact details for notices where appropriate.</p>
PRIVACY,
            'terms' => <<<'TERMS'
<p><strong>Effective September 16, 2026.</strong> Dashless is provided by Izzi’s Gym LLC, doing business as Regionally Famous, South Dakota, United States. Questions, complaints, refund requests and abuse reports: <a href="mailto:howdy@regionallyfamous.com">howdy@regionallyfamous.com</a>.</p>
<h2>The service</h2>
<p>Dashless provides one hosted blog per account and an integration for managing its content and design through ChatGPT. Auth0 handles sign-in using your email address. ChatGPT access is separate and subject to OpenAI’s terms. Features offered by the integration depend on your account’s current access. Dashless does not provide shell access, arbitrary plugins, custom executable themes or team accounts through the app.</p>
<p>You must be an adult able to enter an agreement and may use the service only where legally permitted. Keep your sign-in secure and contact us if you suspect unauthorized access. Do not share an account in a way that exposes another person’s private information.</p>
<h2>Your content and publication</h2>
<p>You retain ownership of your content. You authorize us and the service providers described in our <a href="/privacy/">privacy notice</a> to store, process, build, transmit and display it as necessary to provide your requested service. You are responsible for having the rights and permissions needed for text, images and other material you supply, and for reviewing content before publication. Automated assistance can make mistakes.</p>
<p>Saving a draft or starting a build does not make it public. Publication and rollback require signed-in browser approval of the specific version. Once published, content may be copied or indexed by others. Removing it or rolling back your site cannot retract those independent copies. Maintain your own exports of important content.</p>
<h2>Acceptable use</h2>
<p>Do not use Dashless for unlawful activity, infringement, malware, fraud, harassment, exploitation, disclosure of another person’s private information without authorization, or attempts to evade authentication or access another account. Do not interfere with service availability or submit content you are not permitted to process with our providers. We may restrict access or remove content where necessary to address abuse, security risks or legal requirements. Contact support to report a problem or contest an action.</p>
<h2>Subscriptions, cancellation and refunds</h2>
<p>Where paid signup is available, the advertised plan is US$9.99 per month for one blog; the checkout shows the applicable total and any taxes before purchase. Subscriptions renew monthly until canceled. There is no subscription checkout in the ChatGPT app. Manage payment details and cancellation through the billing portal linked from your Dashless account.</p>
<p>Cancellation takes effect at the end of the paid period. After access expires, the public site is suspended and a 30-day recovery/export period begins before deletion becomes eligible. Failed renewals may receive a seven-day grace period. A canceled ChatGPT subscription and a canceled Dashless subscription are separate actions. Disconnecting the app does not cancel Dashless billing.</p>
<p>If initial paid setup cannot be completed, we investigate and reconcile provisioning before canceling and refunding the failed initial setup. For other refund requests or billing problems, contact support with enough information to identify the account; do not email card numbers. Nothing in these terms limits cancellation, refund or other consumer rights that cannot lawfully be excluded.</p>
<h2>Availability and changes</h2>
<p>Service can be interrupted by maintenance, provider outages or technical failures. We do not promise uninterrupted availability or that automated output will be error-free. We may update features, supported limits or these terms and will provide notice where required. Material billing changes apply only with the notice and choices required by applicable law.</p>
<p>These terms do not exclude rights or remedies available to you under mandatory local law. The service is operated from South Dakota, United States; your mandatory local consumer protections remain applicable where the law provides them. Contact support first so we can investigate and attempt to resolve a dispute.</p>
TERMS,
            default => throw new \InvalidArgumentException('Unknown policy page.'),
        };
    }
}
